/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1dpbo;

import javax.swing.ImageIcon;

/**
 *
 * @author sekar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    dbConnection conn = new dbConnection();
    public Main() {
        initComponents();
        panelUtama.setVisible(true);
        tblBuku.setVisible(true);
        tblAuthor.setVisible(false);
        panelFormAuthor.setVisible(false);
        panelFormBuku.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDataAuthor = new javax.swing.JPanel();
        scrollShowData = new javax.swing.JScrollPane();
        tblAuthor = new javax.swing.JTable();
        paneAuthorImg = new javax.swing.JDesktopPane();
        lblAuthorImg = new javax.swing.JLabel();
        panelUtama = new javax.swing.JPanel();
        btnBuku = new javax.swing.JButton();
        btnAuthor = new javax.swing.JButton();
        tbtnSwitch = new javax.swing.JToggleButton();
        panelFormBuku = new javax.swing.JPanel();
        lblFormAdd = new javax.swing.JLabel();
        lblJudulBuku = new javax.swing.JLabel();
        tfJudulBuku = new javax.swing.JTextField();
        lblPenerbit = new javax.swing.JLabel();
        tfPenerbit = new javax.swing.JTextField();
        lblAuthor = new javax.swing.JLabel();
        cbAuthor = new javax.swing.JComboBox<>();
        lblDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        btnInsertBuku = new javax.swing.JButton();
        lblDesc2 = new javax.swing.JLabel();
        btnCoverBuku = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        panelFormAuthor = new javax.swing.JPanel();
        lblFormAdd1 = new javax.swing.JLabel();
        lblNamaAuthor = new javax.swing.JLabel();
        tfNamaAuthor = new javax.swing.JTextField();
        btnInsertAuthor = new javax.swing.JButton();
        lblNamaAuthor1 = new javax.swing.JLabel();
        btnFotoAuthor = new javax.swing.JButton();
        btnCancel2 = new javax.swing.JButton();
        panelDataBuku = new javax.swing.JPanel();
        scrollShowData1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        paneBukuImg = new javax.swing.JDesktopPane();
        lblBukuImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(365, 600));

        panelDataAuthor.setBackground(new java.awt.Color(204, 204, 255));
        panelDataAuthor.setPreferredSize(new java.awt.Dimension(368, 300));

        scrollShowData.setBackground(new java.awt.Color(245, 230, 230));

        tblAuthor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "Title 2", "Title 3"
            }
        ));
        tblAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAuthorMouseClicked(evt);
            }
        });
        scrollShowData.setViewportView(tblAuthor);

        paneAuthorImg.setPreferredSize(new java.awt.Dimension(120, 100));

        paneAuthorImg.setLayer(lblAuthorImg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneAuthorImgLayout = new javax.swing.GroupLayout(paneAuthorImg);
        paneAuthorImg.setLayout(paneAuthorImgLayout);
        paneAuthorImgLayout.setHorizontalGroup(
            paneAuthorImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
            .addGroup(paneAuthorImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneAuthorImgLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAuthorImg, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        paneAuthorImgLayout.setVerticalGroup(
            paneAuthorImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
            .addGroup(paneAuthorImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneAuthorImgLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAuthorImg, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelDataAuthorLayout = new javax.swing.GroupLayout(panelDataAuthor);
        panelDataAuthor.setLayout(panelDataAuthorLayout);
        panelDataAuthorLayout.setHorizontalGroup(
            panelDataAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAuthorLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(paneAuthorImg, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(panelDataAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDataAuthorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollShowData, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelDataAuthorLayout.setVerticalGroup(
            panelDataAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAuthorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(paneAuthorImg, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(panelDataAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDataAuthorLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(scrollShowData, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelUtama.setBackground(new java.awt.Color(204, 204, 255));

        btnBuku.setBackground(new java.awt.Color(255, 255, 204));
        btnBuku.setText("Add Buku");
        btnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuActionPerformed(evt);
            }
        });

        btnAuthor.setBackground(new java.awt.Color(204, 255, 204));
        btnAuthor.setText("Add Author");
        btnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorActionPerformed(evt);
            }
        });

        tbtnSwitch.setText("Switch");
        tbtnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(tbtnSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAuthor))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(tbtnSwitch)))
                .addContainerGap(530, Short.MAX_VALUE))
        );

        panelFormBuku.setBackground(new java.awt.Color(255, 255, 204));

        lblFormAdd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFormAdd.setText("Form Add Buku");

        lblJudulBuku.setText("Judul Buku");
        lblJudulBuku.setPreferredSize(new java.awt.Dimension(58, 25));

        tfJudulBuku.setPreferredSize(new java.awt.Dimension(71, 25));
        tfJudulBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJudulBukuActionPerformed(evt);
            }
        });

        lblPenerbit.setText("Penerbit");
        lblPenerbit.setPreferredSize(new java.awt.Dimension(58, 25));

        tfPenerbit.setPreferredSize(new java.awt.Dimension(71, 25));

        lblAuthor.setText("Author");
        lblAuthor.setPreferredSize(new java.awt.Dimension(58, 25));

        cbAuthor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAuthor.setMinimumSize(new java.awt.Dimension(72, 25));
        cbAuthor.setPreferredSize(new java.awt.Dimension(72, 25));

        lblDesc.setText("Deskripsi");
        lblDesc.setPreferredSize(new java.awt.Dimension(58, 25));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 86));

        taDesc.setColumns(16);
        taDesc.setRows(5);
        jScrollPane1.setViewportView(taDesc);

        btnInsertBuku.setText("Tambah Data Buku");
        btnInsertBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertBukuActionPerformed(evt);
            }
        });

        lblDesc2.setText("Cover");
        lblDesc2.setPreferredSize(new java.awt.Dimension(58, 25));

        btnCoverBuku.setText("Pilih File");
        btnCoverBuku.setPreferredSize(new java.awt.Dimension(75, 25));
        btnCoverBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoverBukuActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormBukuLayout = new javax.swing.GroupLayout(panelFormBuku);
        panelFormBuku.setLayout(panelFormBukuLayout);
        panelFormBukuLayout.setHorizontalGroup(
            panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormBukuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormAdd)
                .addGap(94, 94, 94))
            .addGroup(panelFormBukuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormBukuLayout.createSequentialGroup()
                        .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFormBukuLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFormBukuLayout.createSequentialGroup()
                                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPenerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblJudulBuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDesc2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormBukuLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(tfJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormBukuLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCoverBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(20, 20, 20))
                    .addGroup(panelFormBukuLayout.createSequentialGroup()
                        .addComponent(btnInsertBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelFormBukuLayout.setVerticalGroup(
            panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormBukuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblFormAdd)
                .addGap(27, 27, 27)
                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCoverBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelFormBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        panelFormAuthor.setBackground(new java.awt.Color(204, 255, 204));
        panelFormAuthor.setPreferredSize(new java.awt.Dimension(356, 791));

        lblFormAdd1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFormAdd1.setText("Form Add Author");

        lblNamaAuthor.setText("Nama");
        lblNamaAuthor.setPreferredSize(new java.awt.Dimension(58, 25));

        tfNamaAuthor.setPreferredSize(new java.awt.Dimension(71, 25));
        tfNamaAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaAuthorActionPerformed(evt);
            }
        });

        btnInsertAuthor.setText("Tambah Data Author");
        btnInsertAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertAuthorActionPerformed(evt);
            }
        });

        lblNamaAuthor1.setText("Foto");
        lblNamaAuthor1.setPreferredSize(new java.awt.Dimension(58, 25));

        btnFotoAuthor.setText("Pilih File");
        btnFotoAuthor.setPreferredSize(new java.awt.Dimension(75, 25));
        btnFotoAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoAuthorActionPerformed(evt);
            }
        });

        btnCancel2.setText("Cancel");
        btnCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormAuthorLayout = new javax.swing.GroupLayout(panelFormAuthor);
        panelFormAuthor.setLayout(panelFormAuthorLayout);
        panelFormAuthorLayout.setHorizontalGroup(
            panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormAuthorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFormAdd1)
                .addGap(84, 84, 84))
            .addGroup(panelFormAuthorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormAuthorLayout.createSequentialGroup()
                        .addGroup(panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormAuthorLayout.createSequentialGroup()
                                .addComponent(lblNamaAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormAuthorLayout.createSequentialGroup()
                                .addComponent(lblNamaAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNamaAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFotoAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFormAuthorLayout.createSequentialGroup()
                        .addComponent(btnInsertAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelFormAuthorLayout.setVerticalGroup(
            panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormAuthorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblFormAdd1)
                .addGap(28, 28, 28)
                .addGroup(panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamaAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFotoAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelFormAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(396, Short.MAX_VALUE))
        );

        panelDataBuku.setBackground(new java.awt.Color(204, 204, 255));
        panelDataBuku.setPreferredSize(new java.awt.Dimension(368, 300));

        scrollShowData1.setBackground(new java.awt.Color(245, 230, 230));

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Judul Buku", "Penerbit", "Author", "Deskripsi"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        scrollShowData1.setViewportView(tblBuku);
        if (tblBuku.getColumnModel().getColumnCount() > 0) {
            tblBuku.getColumnModel().getColumn(0).setMinWidth(30);
            tblBuku.getColumnModel().getColumn(0).setMaxWidth(30);
            tblBuku.getColumnModel().getColumn(0).setHeaderValue("No");
            tblBuku.getColumnModel().getColumn(1).setHeaderValue("Nama");
            tblBuku.getColumnModel().getColumn(2).setHeaderValue("Jumlah Buku");
        }

        paneBukuImg.setPreferredSize(new java.awt.Dimension(120, 100));

        paneBukuImg.setLayer(lblBukuImg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout paneBukuImgLayout = new javax.swing.GroupLayout(paneBukuImg);
        paneBukuImg.setLayout(paneBukuImgLayout);
        paneBukuImgLayout.setHorizontalGroup(
            paneBukuImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
            .addGroup(paneBukuImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBukuImgLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblBukuImg, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        paneBukuImgLayout.setVerticalGroup(
            paneBukuImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
            .addGroup(paneBukuImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneBukuImgLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblBukuImg, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelDataBukuLayout = new javax.swing.GroupLayout(panelDataBuku);
        panelDataBuku.setLayout(panelDataBukuLayout);
        panelDataBukuLayout.setHorizontalGroup(
            panelDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataBukuLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(paneBukuImg, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(panelDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDataBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollShowData1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelDataBukuLayout.setVerticalGroup(
            panelDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataBukuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(paneBukuImg, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(panelDataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDataBukuLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(scrollShowData1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelFormBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelFormAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDataAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDataBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelFormBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelFormAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(panelDataAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(118, Short.MAX_VALUE)
                    .addComponent(panelDataBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(68, 68, 68)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfJudulBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJudulBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJudulBukuActionPerformed

    private void tfNamaAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaAuthorActionPerformed

    private void btnInsertAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertAuthorActionPerformed
        // TODO add your handling code here:
        panelFormAuthor.setVisible(false);
        panelFormBuku.setVisible(false);
        panelUtama.setVisible(true);
    }//GEN-LAST:event_btnInsertAuthorActionPerformed

    private void btnCoverBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoverBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoverBukuActionPerformed

    private void btnFotoAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFotoAuthorActionPerformed

    private void tbtnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSwitchActionPerformed
        // TODO add your handling code here:
        if(tbtnSwitch.isSelected()) {
//            tblAuthor.setModel(conn.readTable());
            String q = "SELECT author_nama, author_jumlah_buku FROM author;";
            Object[] theads = {"No.", "Nama", "Jumlah"};
            Object[] columns = {"author_id","author_nama", "author_jumlah_buku"};
            tblAuthor.setModel(conn.readTable(theads, columns, q));

            panelUtama.setVisible(true);
            panelDataAuthor.setVisible(true);
            tblAuthor.setVisible(true);
            paneAuthorImg.setVisible(false);
        } else {
            panelDataBuku.setVisible(true);
            panelDataAuthor.setVisible(false);
            String q = "SELECT buku.buku_judul, buku.buku_penerbit, author.author_nama, buku.buku_desc FROM buku JOIN author ON buku.author_id=author.author_id;";
            Object[] theads = {"No.", "Judul Buku", "Penerbit", "Author", "Deskripsi"};
            Object[] columns = {"buku.buku_id","buku.buku_judul", "buku.buku_penerbit", "author.author_nama", "buku.buku_desc"};
            tblBuku.setModel(conn.readTable(theads, columns, q));
            
            panelDataAuthor.setVisible(false);
            System.out.println("button unselected");
        }
        
    }//GEN-LAST:event_tbtnSwitchActionPerformed

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed
        // TODO add your handling code here:
        panelUtama.setVisible(false);
        panelFormAuthor.setVisible(false);
        panelFormBuku.setVisible(true);
    }//GEN-LAST:event_btnBukuActionPerformed

    private void btnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorActionPerformed
        // TODO add your handling code here:
        panelUtama.setVisible(false);
        panelFormBuku.setVisible(false);
        panelFormAuthor.setVisible(true);
    }//GEN-LAST:event_btnAuthorActionPerformed

    private void btnInsertBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertBukuActionPerformed
        // TODO add your handling code here:
        panelFormBuku.setVisible(false);
        panelFormAuthor.setVisible(false);
        panelUtama.setVisible(true);
    }//GEN-LAST:event_btnInsertBukuActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        panelFormBuku.setVisible(false);
        panelFormAuthor.setVisible(false);
        panelUtama.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel2ActionPerformed
        // TODO add your handling code here:
        panelFormAuthor.setVisible(false);
        panelFormBuku.setVisible(false);
        panelUtama.setVisible(true);
    }//GEN-LAST:event_btnCancel2ActionPerformed

    private void tblAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAuthorMouseClicked
        // TODO add your handling code here:
        int row = tblAuthor.getSelectedRow();
        String tblClicked = tblAuthor.getModel().getValueAt(row, 1).toString();
        
        try {
            paneAuthorImg.setVisible(true);
            String sql = "SELECT author_img FROM author WHERE author_nama = '" + tblClicked + "';";
            lblAuthorImg.setIcon(conn.showImage(sql, "author_img"));
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblAuthorMouseClicked

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        // TODO add your handling code here:
        int row = tblBuku.getSelectedRow();
        String tblClicked = tblBuku.getModel().getValueAt(row, 1).toString();
        dbConnection conn = new dbConnection();
        
        try {
            paneBukuImg.setVisible(true);
            String sql = "SELECT buku_img FROM buku WHERE buku_judul = '" + tblClicked + "';";
            lblBukuImg.setIcon(conn.showImage(sql, "buku_img"));
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthor;
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel2;
    private javax.swing.JButton btnCoverBuku;
    private javax.swing.JButton btnFotoAuthor;
    private javax.swing.JButton btnInsertAuthor;
    private javax.swing.JButton btnInsertBuku;
    private javax.swing.JComboBox<String> cbAuthor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblAuthorImg;
    private javax.swing.JLabel lblBukuImg;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDesc2;
    private javax.swing.JLabel lblFormAdd;
    private javax.swing.JLabel lblFormAdd1;
    private javax.swing.JLabel lblJudulBuku;
    private javax.swing.JLabel lblNamaAuthor;
    private javax.swing.JLabel lblNamaAuthor1;
    private javax.swing.JLabel lblPenerbit;
    private javax.swing.JDesktopPane paneAuthorImg;
    private javax.swing.JDesktopPane paneBukuImg;
    private javax.swing.JPanel panelDataAuthor;
    private javax.swing.JPanel panelDataBuku;
    private javax.swing.JPanel panelFormAuthor;
    private javax.swing.JPanel panelFormBuku;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JScrollPane scrollShowData;
    private javax.swing.JScrollPane scrollShowData1;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTable tblAuthor;
    private javax.swing.JTable tblBuku;
    private javax.swing.JToggleButton tbtnSwitch;
    private javax.swing.JTextField tfJudulBuku;
    private javax.swing.JTextField tfNamaAuthor;
    private javax.swing.JTextField tfPenerbit;
    // End of variables declaration//GEN-END:variables
}
